#!/bin/bash

echo "🧪 Portal Testing Guide"
echo "======================"
echo ""
echo "After the SQL fix, test these URLs:"
echo ""
echo "✅ Home Page:"
echo "   http://localhost:8000/portal"
echo ""
echo "✅ Category Page (should work now):"
echo "   http://localhost:8000/portal/category"
echo ""
echo "✅ Customer Management:"
echo "   http://localhost:8000/portal/profile"
echo ""
echo "✅ Cart Page:"
echo "   http://localhost:8000/portal/cart"
echo ""
echo "✅ Bookings:"
echo "   http://localhost:8000/portal/bookings"
echo ""
echo "🔍 Test Flow:"
echo "1. Go to /portal (home)"
echo "2. Click 'Browse' in bottom nav"
echo "3. Go to /portal/profile"
echo "4. Try creating a customer"
echo "5. Navigate between pages"
echo ""
echo "🐛 If you see errors:"
echo "- Check browser console"
echo "- Check server logs"
echo "- Verify database has Items and Categories"
echo ""
